### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by shapr** [christian-blades-cb/maclight#1]
I suspect I'm using the wrong version of rust and possibly cargo, is there some way to declare required versions in the Cargo.toml?

```error[E0015]: calls in statics are limited to struct and enum constructors
  --> src/main.rs:19:41
   |
19 | static HUNDRED_MILLIS: time::Duration = time::Duration::from_millis(100);
```

**Comment by christian-blades-cb** [comment]
@shapr I'm building with stable 1.25 and also checking against nightly. I'm unaware of a way to define a minimum version, but maybe adding travis.ci would help?

**Comment by shapr** [comment]
My fault, my $PATH was wrong, I was using an antique version of rustc!
